server:
  port: 9091
logging:
  level:
    root: WARN
    io.streamnative: INFO
    org.apache.pulsar.common.util.netty: ERROR
spring:
  pulsar:
    defaults:
      type-mappings: 
        - message-type: io.streamnative.pulsarbeerfactory.delivery.DeliveryOrder
          schema-info:
            schema-type: JSON
