version: '2'

services:
  pulsar:
    image: apachepulsar/pulsar:3.0.0
    command: bin/pulsar standalone
    ports:
      - '6650:6650'
      - '8080:8080'
  redis:
    image: docker.io/bitnami/redis:7.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
#    volumes:
#      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local
